
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtrnxishuraqzsrvbzwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10cm54aXNodXJhcXpzcnZiendtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Mzc4OTUsImV4cCI6MjA2MTMxMzg5NX0.gRxCCqf_LcPvzDkljh9zhse2I90fPtCXE4neBZs6wrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      storageKey: 'supabase.auth.token'
    }
  }
);
